### ISSUE TITLE
getRayPaths

### ISSUE THREAD

**Issue by cecidip** [gimli-org/pyGIMLi#394]
### Problem description

I needed to use the raypaths so i implemented a little function getRaypaths on my version of TravelTimeManager.py. If you're interested in implementing it i could do a pull request.
![Screen Shot 2022-06-03 at 10 08 53 AM](https://user-images.githubusercontent.com/22650615/171870618-8ca05de0-3099-4741-89a7-61091d13ddd3.png)

![Screen Shot 2022-06-03 at 10 09 41 AM](https://user-images.githubusercontent.com/22650615/171870774-47bd69af-c2be-402e-8685-6de1abf58105.png)

If there already was a function and i didn't realize, im sorry. 

Thanks, 

Ceci

**Comment by halbmy** [comment]
Sorry for the late response. Yes, that's a good idea to have a function that generates the ray paths (with the optional model vector) for more systematic studies.

**Comment by cecidip** [comment]
This is the code i'm using wight now, i added it to TravelTimeManager.py

    `def getRayPaths(self,model=None):

        Returns
        -------
        segs: raypaths
        """
        if model is not None:
            if self.fop.jacobian().size() == 0 or model != self.model:
                self.fop.createJacobian(1/model)
        else:
            model = self.model


        shots = self.fop.data.id("s")
        recei = self.fop.data.id("g")

        segs = []
        for s, g in zip(shots, recei):
            wi = self.fop.way(s, g)
            points = self.fop._core.mesh().positions(withSecNodes=True)[wi]
            segs.append(np.column_stack((pg.x(points), pg.y(points))))


        return segs`

and i call it from my script: 
`Rays=mgr.getRayPaths()`

Hope it helps!

**Comment by halbmy** [comment]
Yes that's the code that's already in drawRayPaths. I will update the class accordingly. Thank your for this nice idea!

**Comment by halbmy** [comment]
Added `getRayPaths()` function #4fc2a5a
