### ISSUE TITLE
Passing area to mesh generation not working as intended

### ISSUE THREAD

**Issue by GGDRriedel** [gimli-org/pyGIMLi#407]
### Problem description

I am trying to give a user control over mesh cell areas. 

However passing it like so 

```python
mesh=ras.createMesh(data=data,
                    paraDepth=50,
                    area=1000,
                    quality=20)

```
Does not result in a very COARSE mesh 

This seems due to this part in mesh.py
```python
 plc = pg.meshtools.createParaMeshPLC(*args, **kwargs)
    kwargs.pop('paraMaxCellSize', 0)
    kwargs.pop('boundaryMaxCellSize', 0)
    smooth = kwargs.pop('smooth', [2, 10])
    mesh = createMesh(plc, **kwargs, smooth=smooth)
    return mesh
```

createParaMeshPLC expects " paraMaxCellSize"

So giving "area=1000" to createMesh  results in a rather fine ParaMesh, even though my area is at 10000 and quality pretty low. 

Now giving it " paraMaxCellSize=1000" in turn creates a sufficiently coarse PLC, but of course makes
```createMesh(plc, **kwargs, smooth=smooth)```
not see an ```area``` parameter and results still in a very fine mesh.

I have circumvented this by calling it  like so

```python

mesh=ras.createMesh(data=data,
                    paraDepth=50,
                    area=1000,
                    paraMaxCellSize=1000,
                    quality=20)
```
This results in each function getting the right "large" value. 

### Your environment
pg 1.2.6 windows

**Comment by carsten-forty2** [comment]
I think I don't get the problem and I don't now what `ras` should be, there are some `createMesh` with a different default behaviour depending on the specific needs of the caller.

`createParaMeshPLC` sets regionmarker to force local maximum cell sizes for the parametric region (`paraMaxCellSize`) and for the outer boundary region (`boundaryMaxCellSize`)

`area` sets the global maximum cell size according to the `triangle` -a switch. I'm not sure about `triangle`s behaviour if you mix both.

**Comment by GGDRriedel** [comment]
```ras``` is my instanced traveltime manager object. 

I am not the one mixing them, it's the code called by createMesh that 's mixing them in travetimemanager.py and subsequently the ```createMesh``` method calling ```pg.meshtools.createParaMesh``` resulting in 


```python 
 plc = pg.meshtools.createParaMeshPLC(*args, **kwargs)
    kwargs.pop('paraMaxCellSize', 0)
    kwargs.pop('boundaryMaxCellSize', 0)
    smooth = kwargs.pop('smooth', [2, 10])
    mesh = createMesh(plc, **kwargs, smooth=smooth)
```
in mesh.py as I described up there.

**Comment by halbmy** [comment]
As @carsten-forty2 explained, there is a local setting for the maximum area in each region (using `paraMaxCellSize`) and a global one (using `area`). How they are mixed, is the matter of triangle. I would recommend using the one or the other, but not both. Can you provide an example with given points (generated by numpy) so that we can understand the problem?

**Comment by GGDRriedel** [comment]
tbh. I have no clue how to get np arrays into a TT manager object as data container as I can't really find an example on how to do it or documentation on how to manipulate that container directly, I always do it by reading files as that is the way I can find as examples.

Can you provide what ```ttmanagerobject=pg.physics.Refraction(data=dataarray)```expects for ```dataarray```? 
I'd gladly make an example.

**Comment by carsten-forty2** [comment]
It might be possible to demonstrate your problem using the example from the documentation: https://www.pygimli.org/pygimliapi/_generated/pygimli.meshtools.html?highlight=createparameshplc#createparameshplc

**Comment by GGDRriedel** [comment]
I don't know how because I am using the createmesh Method of a TT-Manager object

**Comment by halbmy** [comment]
The `TravelTimeManager.createMesh` just uses the `pg.meshtools.createMesh` with the sensors in the data

**Comment by carsten-forty2** [comment]
you refer twice to `createParaMeshPLC` and the acompanied code for the traveltime mesh creation .. so you just need copy & paste the example code from the apidoc to see/show how the arguments work. If you don't show us what do mean goes wrong, we can't see the issue and cannot help with it.

**Comment by GGDRriedel** [comment]
> The `TravelTimeManager.createMesh` just uses the `pg.meshtools.createMesh` with the sensors in the data

No. It uses  pg.meshtools.createParaMesh. 

Which in turn first calls  ```plc = pg.meshtools.createParaMeshPLC(*args, **kwargs)```
Which does NOT take area as an argument. 

It takes paraMaxCellSize

And THEN puts that PLC into  ```pg.meshtools.createMesh```

in line 1777 ``` mesh = createMesh(plc, **kwargs, smooth=kwargs.pop('smooth', [2, 10]))```
