### ISSUE TITLE
module 'pygimli.physics.ert' has no attribute 'estimateError'

### ISSUE THREAD

**Issue by sadalan97** [gimli-org/pyGIMLi#511]
### Problem description

Hello, I'm doing some initial steps in geoelectric data processing with the Wenner array. however, when estimating the error from the data, I get an error as if pygimligi doesn't have this method for the calculation. Could anyone help me with this problem? Grateful.

### Steps to reproduce

```python
import matplotlib.pyplot as plt

import numpy as np

import pybert as pb

import pygimli as pg

import pygimli.meshtools as mt

from pygimli.physics import ert

data = ert.load("./bert_teste/SBWenner.dat")
data["k"] = ert.createGeometricFactors(data)
k_num = ert.createGeometricFactors(data, numerical=True)
k_ana = ert.createGeometricFactors(data, numerical=False)

data["k"] = ert.createGeometricFactors(data)
print(data)
ert.show(data, "valid");
ert.show(data, "k");
ert.show(data, "rhoa");

data["err"] = ert.estimateError(data, relativeError=0.02, absoluteUError=1e-4)
# print(max(data["err"]))
...
```

### Real Behavior

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[17], line 1
----> 1 data["err"] = ert.estimateError(data, relativeError=0.02, absoluteUError=1e-4)
      2 print(max(data["err"]))

AttributeError: module 'pygimli.physics.ert' has no attribute 'estimateError'
```

**Comment by halbmy** [comment]
Which pyGIMLi version are you using (`pg.__version__`)? I suspect that you have an old version where this function was only in the manager
```
mgr = ert.ERTManager()
mgr.estimateError(...
```
Try updating to a recent version (currently 1.3.1).

**Comment by LessandroValente** [comment]
Hi Gunther.

Thanks for your return. I'm using pygimli inside the BERT environment
activated in my terminal. I made the update but it seems that it is out of
this environment. Do you have any idea how I can perform this update within
the BERT environment?

**Comment by halbmy** [comment]
You can either activate the env and update inside
```
conda activate bert
conda update pygimli # or
# conda install pygimli=1.3.1
```
or from outside by `conda update -n bert pygimli` or `conda install -n bert pygimli=1.3.1`

**Comment by LessandroValente** [comment]
Now it worked without problems, thank you very much.
